{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Planned\",\"Produced\",\"dataSource\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.131.901.0 (24.07)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "en-US",
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "dataSource",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ],
        "expression": "\"C:\\repositories\\pro2future-event-table-viewer\\Example Report\\\" meta [IsParameterQuery=true, Type=\"Any\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "206d40ac-f050-4b66-9b70-c43c91c8a31c"
      }
    ],
    "relationships": [
      {
        "name": "91486a5d-c48a-4099-854d-a2ce782ba748",
        "fromColumn": "Event A",
        "fromTable": "Produced",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_59f86076-e694-4dea-b06a-449c8eb0543d"
      },
      {
        "name": "5a8bf5a8-b64e-44ec-b8c7-9e67b80b54bc",
        "fromColumn": "Shipping Date",
        "fromTable": "Produced",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_d964019d-583b-4728-a34d-8816bada53dd"
      },
      {
        "name": "4c75c83f-9c64-4085-bf3a-f15f1bbba645",
        "fromColumn": "Event C",
        "fromTable": "Produced",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_028f321c-c6f0-4acc-9645-620ebd44f9bd"
      },
      {
        "name": "a7d99658-8d9d-48cf-9eb0-db8f5d47ae80",
        "fromColumn": "Event D",
        "fromTable": "Produced",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_d231e8cc-b6e1-4aeb-ba99-9dfd011195ca"
      },
      {
        "name": "3fc13253-395f-40e0-9e74-b9b566f6f888",
        "fromColumn": "Event B",
        "fromTable": "Produced",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_d5950262-fe10-4a8b-8a21-c5c60762f765"
      },
      {
        "name": "2cae3ae0-bad9-4edb-9a48-f71bf3675118",
        "fromColumn": "Event A",
        "fromTable": "Planned",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_d85d4649-8aa3-4301-bd22-0e3c32565b8c"
      },
      {
        "name": "f66f6047-6907-4e10-9ff5-99216a1a06c4",
        "fromColumn": "Event D",
        "fromTable": "Planned",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_806dce84-153c-4eb1-a52a-37e471658132"
      },
      {
        "name": "1e82d2dd-231b-4018-b514-ab16e67d0f3b",
        "fromColumn": "Shipping Date",
        "fromTable": "Planned",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_09d7d9f5-9c46-4024-8288-33bda2c9c17e"
      },
      {
        "name": "6f9c6a39-9380-47ad-9c45-b8307bbb0819",
        "fromColumn": "Event C",
        "fromTable": "Planned",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_f6d0dca3-3150-434d-9035-75bd2bc88740"
      }
    ],
    "sourceQueryCulture": "de-AT",
    "tables": [
      {
        "name": "Planned",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "35acbeea-75dd-4c50-92ca-b122d0cbc5a3",
            "sourceColumn": "ID",
            "summarizeBy": "count"
          },
          {
            "name": "Event A",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f94db65c-7c11-4f0b-a90f-8eee4141456a",
            "sourceColumn": "Event A",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_d85d4649-8aa3-4301-bd22-0e3c32565b8c"
                },
                "isDefault": true,
                "relationship": "2cae3ae0-bad9-4edb-9a48-f71bf3675118"
              }
            ]
          },
          {
            "name": "Event D",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "7be182a3-d888-43fa-b6e2-016b47c9c1cf",
            "sourceColumn": "Event D",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_806dce84-153c-4eb1-a52a-37e471658132"
                },
                "isDefault": true,
                "relationship": "f66f6047-6907-4e10-9ff5-99216a1a06c4"
              }
            ]
          },
          {
            "name": "Shipping Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "cdd9110c-e49f-4aef-9e05-58cdcf290c58",
            "sourceColumn": "Shipping Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_09d7d9f5-9c46-4024-8288-33bda2c9c17e"
                },
                "isDefault": true,
                "relationship": "1e82d2dd-231b-4018-b514-ab16e67d0f3b"
              }
            ]
          },
          {
            "name": "Event C",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "30af3e3c-ceff-4886-88c1-065e58b36de6",
            "sourceColumn": "Event C",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_f6d0dca3-3150-434d-9035-75bd2bc88740"
                },
                "isDefault": true,
                "relationship": "6f9c6a39-9380-47ad-9c45-b8307bbb0819"
              }
            ]
          },
          {
            "name": "Width",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "5c9d024c-4bfd-4397-83f1-88589eda5155",
            "sourceColumn": "Width",
            "summarizeBy": "sum"
          },
          {
            "name": "Height",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "ef4f1c5b-8e2e-4c39-b81c-c01c4926c2a2",
            "sourceColumn": "Height",
            "summarizeBy": "sum"
          },
          {
            "name": "Warehouse",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "7d31641c-5635-4525-a6c8-8e2f73d57a39",
            "sourceColumn": "Warehouse",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "a8bb2347-76a1-4a3e-8bfc-35ac7ee2e2f6",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "Is Event D",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "743a847c-b335-43f2-839a-c72d06a2b541",
            "sourceColumn": "Is Event D",
            "summarizeBy": "none"
          },
          {
            "name": "ID similar",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "4c91c753-0997-43c2-9cc3-f7680ab0f971",
            "sourceColumn": "ID similar",
            "summarizeBy": "none"
          },
          {
            "name": "Duration Similar",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1c7635f9-82c5-4545-924e-6ffdb33831bb",
            "sourceColumn": "Duration Similar",
            "summarizeBy": "none"
          },
          {
            "name": "Current Warehouse",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "26f1fe84-d7ac-4951-a044-a6b69fd3c0fc",
            "sourceColumn": "Current Warehouse",
            "summarizeBy": "none"
          }
        ],
        "lineageTag": "7d899d8c-749d-4c52-857a-57ea039ccf0d",
        "partitions": [
          {
            "name": "Planned",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(dataSource & \"sample data.xlsx\"), null, true),",
                "    Planned_Table = Source{[Item=\"Planned\",Kind=\"Table\"]}[Data],",
                "    ",
                "    MinDate = List.Min(Planned_Table[Event A]),",
                "    CurrentDate = Date.From(DateTime.LocalNow()),",
                "    DateDifference = Duration.From(CurrentDate - MinDate),",
                "    AdjustedDates = Table.TransformColumns(",
                "        Planned_Table,",
                "        List.Transform(",
                "            Table.ColumnNames(Planned_Table),",
                "            each {_, each if Value.Is(_, type date) then Date.AddDays(_, Duration.Days(DateDifference)-50) else _}",
                "        )",
                "    ),",
                "    #\"Set Null Dates\" = Table.ReplaceValue(AdjustedDates,each[Event D],each if Date.Year(Date.From([Event D])) < 2007 then null else [Date], Replacer.ReplaceValue, {\"Event D\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Set Null Dates\",{{\"ID\", Int64.Type}, {\"Event A\", type date}, {\"Event D\", type date}, {\"Shipping Date\", type date}, {\"Event C\", type date}, {\"Width\", type number}, {\"Height\", type number}, {\"Warehouse\", type text}, {\"Category\", type text}, {\"IsD\", type logical}, {\"ID similar\", type text}, {\"Duration Similar\", type text}}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Changed Type\",{{\"IsD\", \"Is Event D\"}})",
                "in",
                "    #\"Renamed Columns\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_1c476de5-f998-460f-8556-e0e427edfdfb",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "44296744-fa4a-4663-bcf2-14d30b493e82",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "9eae4433-ba8c-4c71-8fae-1c2bc74cdee1",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "467de5db-ba6d-42ab-be0b-1afbe691625f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "97b296f3-b7d0-4116-bc0c-3f1f9d72beab",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "789ec66f-e862-4a63-a4b0-00d2e6af5b51",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "577f9459-a307-4fb2-a6ff-085b1d7d05c5",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "7f351dbf-b78c-4f5c-ae7a-f2e2e431a37c",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "22baf7d1-426e-48a6-897e-b538ad101b77",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "811fbcfb-dd6c-481e-b396-b1fc02f0072e",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "732f215e-fc35-4d94-96aa-8fb4eb2384d2",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "53b26202-43c4-4f16-b765-a3d9b1ba5abd",
                "ordinal": 3
              }
            ],
            "lineageTag": "a8582904-ad34-467d-ad0e-e754c4bc5a49"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "8e06cb11-5664-48ee-a706-a6a2f7b2a4ef",
        "partitions": [
          {
            "name": "DateTableTemplate_1c476de5-f998-460f-8556-e0e427edfdfb",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "Produced",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          }
        ],
        "columns": [
          {
            "name": "ID",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "int64",
            "formatString": "0",
            "lineageTag": "1da54fdd-4da7-45e2-a9a9-3fb09138f88c",
            "sourceColumn": "ID",
            "summarizeBy": "count"
          },
          {
            "name": "Event A",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "ed7844cb-e4f5-4058-bb7a-6b327198282e",
            "sourceColumn": "Event A",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_59f86076-e694-4dea-b06a-449c8eb0543d"
                },
                "isDefault": true,
                "relationship": "91486a5d-c48a-4099-854d-a2ce782ba748"
              }
            ]
          },
          {
            "name": "Event B",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "dateTime",
            "formatString": "General Date",
            "lineageTag": "e010db95-868a-4384-82f4-700cda46c8c3",
            "sourceColumn": "Event B",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_d5950262-fe10-4a8b-8a21-c5c60762f765"
                },
                "isDefault": true,
                "relationship": "3fc13253-395f-40e0-9e74-b9b566f6f888"
              }
            ]
          },
          {
            "name": "Event D",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "c824ea3c-b098-4def-9355-ace863d9657e",
            "sourceColumn": "Event D",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_d231e8cc-b6e1-4aeb-ba99-9dfd011195ca"
                },
                "isDefault": true,
                "relationship": "a7d99658-8d9d-48cf-9eb0-db8f5d47ae80"
              }
            ]
          },
          {
            "name": "Shipping Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "faf6942b-730d-41cd-bf4e-51a151a36a92",
            "sourceColumn": "Shipping Date",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_d964019d-583b-4728-a34d-8816bada53dd"
                },
                "isDefault": true,
                "relationship": "5a8bf5a8-b64e-44ec-b8c7-9e67b80b54bc"
              }
            ]
          },
          {
            "name": "Event C",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "64ee7184-9829-46af-8596-a66ac81abbd9",
            "sourceColumn": "Event C",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Date Hierarchy",
                  "table": "LocalDateTable_028f321c-c6f0-4acc-9645-620ebd44f9bd"
                },
                "isDefault": true,
                "relationship": "4c75c83f-9c64-4085-bf3a-f15f1bbba645"
              }
            ]
          },
          {
            "name": "Width",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "51d4977f-075f-4958-a8e9-679d0a7557ef",
            "sourceColumn": "Width",
            "summarizeBy": "sum"
          },
          {
            "name": "Height",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "1b65202a-927c-4858-bc9f-d07f5fee9aae",
            "sourceColumn": "Height",
            "summarizeBy": "sum"
          },
          {
            "name": "Warehouse",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ee251a9e-f06a-4442-93e6-fe53b6bb3d67",
            "sourceColumn": "Warehouse",
            "summarizeBy": "none"
          },
          {
            "name": "Category",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "d20c6252-2cff-46a6-8f84-9a8d39e90112",
            "sourceColumn": "Category",
            "summarizeBy": "none"
          },
          {
            "name": "IsD",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "boolean",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "lineageTag": "cb36a318-d183-4f62-ac88-808301fa4acb",
            "sourceColumn": "IsD",
            "summarizeBy": "none"
          },
          {
            "name": "Duration",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ],
            "dataType": "double",
            "lineageTag": "39b1c117-7c3d-4cd1-9eea-72f0ebdac3b8",
            "sourceColumn": "Duration",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "a1072f33-7c05-430c-bc4a-7efc38324a9c",
        "partitions": [
          {
            "name": "Produced",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Source = Excel.Workbook(File.Contents(dataSource&\"sample data.xlsx\"), null, true),",
                "    Produced_Table = Source{[Item=\"Produced\",Kind=\"Table\"]}[Data],",
                "    #\"Set Null Dates\" = Table.ReplaceValue(Produced_Table,each[Event D],each if Date.Year(Date.From([Event D])) < 2007 then null else [Date], Replacer.ReplaceValue, {\"Event D\"}),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Set Null Dates\",{{\"ID\", Int64.Type}, {\"Event A\", type date}, {\"Event B\", type datetime}, {\"Event D\", type date}, {\"Shipping Date\", type date}, {\"Event C\", type date}, {\"Width\", type number}, {\"Height\", type number}, {\"Warehouse\", type text}, {\"Category\", type text}, {\"IsD\", type logical}, {\"Duration\", type number}})",
                "in",
                "    #\"Changed Type\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_59f86076-e694-4dea-b06a-449c8eb0543d",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "2bcc716e-4713-40c9-a45c-b33dd36686fd",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "cda3df24-db6c-40a3-972f-16bd7215657a",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "198150be-4f83-48b9-a55e-8dc4e9a18124",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "426063b4-005e-4783-8cf6-347ba98ac5a2",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "2fc19749-6bd4-4108-a111-99a86f9f1240",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "8158e0de-dfa6-4cd7-9253-5d695db5e842",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "fe47d544-a50f-4c88-9759-aadaf0565da1",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "7c2679e4-2f49-4f8d-9be8-6a18b8fcc06b",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d700f6a6-96fc-463d-bf57-cd58f5513b50",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "3da4c725-684d-4296-8514-a44287adb48b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "d3bd38e3-2e5a-4433-8441-57f9e019c595",
                "ordinal": 3
              }
            ],
            "lineageTag": "7e600742-e4c7-449b-bffb-9e7a3c69f426"
          }
        ],
        "isHidden": true,
        "lineageTag": "8c008f74-eeaa-4e55-8e2c-eb31deb27f30",
        "partitions": [
          {
            "name": "LocalDateTable_59f86076-e694-4dea-b06a-449c8eb0543d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Produced'[Event A])), 1, 1), Date(Year(MAX('Produced'[Event A])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_d964019d-583b-4728-a34d-8816bada53dd",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "5f92664c-9453-411b-a7eb-969da14f478c",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "3070b496-ca34-417e-8eb3-e52a3a59d573",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "1dbd0214-da60-46f7-9063-e507ead59566",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "69712cb7-2e8b-4d2f-b9f1-a113efa8edd4",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "1cc14ef8-5164-4d44-b3d1-b7f66f169261",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "0233d555-10a3-4a7c-9454-d7da8743b017",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "3f6d9f84-bec5-462c-8060-ca814c035d92",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a376eceb-5208-42df-a65d-6c01bc92d513",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "39177887-c477-4916-ab66-bc6cefe062fa",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "0cdc3b2a-f6c9-41d9-a7cf-52d591f71bd4",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "a2ad478d-ff4a-403c-af43-989f3efcc9a2",
                "ordinal": 3
              }
            ],
            "lineageTag": "47b62986-c5fa-4e48-9d9a-e45329ea5e91"
          }
        ],
        "isHidden": true,
        "lineageTag": "d27bfaf7-1c1e-4887-8798-3ad38be56a02",
        "partitions": [
          {
            "name": "LocalDateTable_d964019d-583b-4728-a34d-8816bada53dd",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Produced'[Shipping Date])), 1, 1), Date(Year(MAX('Produced'[Shipping Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_028f321c-c6f0-4acc-9645-620ebd44f9bd",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f1e50158-a3cf-40c3-bff0-f7f5df1341fc",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "e20a5ba3-ec33-4ee5-8fb3-b3b4e979da71",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "4479f75d-4672-4cac-b32a-7f7037105cb8",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "bf4b95f6-0ef6-466e-9f80-4ee3e8a499ea",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "6396f058-8d91-445b-82eb-70b2d4ea31b5",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "000f4c0e-2b37-48f9-8cbf-3194dc7f7571",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "44a87d62-6380-483d-8957-7de9e13e6950",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a32dfadf-ac34-4e4d-9f62-9f54af922380",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "c19e691e-96d1-4ac4-8353-20cf16e8f5db",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "fd6e94ac-b4f0-470d-91b6-f323a5dd1b4b",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "e056c4f8-c5d6-4b3e-bd2b-3bd87edad77e",
                "ordinal": 3
              }
            ],
            "lineageTag": "50ab1178-3512-4e7b-8371-c5c159ce35de"
          }
        ],
        "isHidden": true,
        "lineageTag": "81bbd771-34d3-438e-b09c-f2c8bfa60844",
        "partitions": [
          {
            "name": "LocalDateTable_028f321c-c6f0-4acc-9645-620ebd44f9bd",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Produced'[Event C])), 1, 1), Date(Year(MAX('Produced'[Event C])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_d231e8cc-b6e1-4aeb-ba99-9dfd011195ca",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "a8f03c5e-04ae-43b6-90b6-6725197f6817",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "eb86fd66-0fdc-458f-a9fa-80cffc7a5875",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "927b6c07-a5e1-4b63-9b3e-030cc669dc5d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "b7ce1c9a-d0f9-4d9a-b569-f637736a3880",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "88c30081-5e94-4540-a87b-2d71fdc40961",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "5271a8ef-fd1d-4790-b54b-374d16b154ec",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "72533da1-44b6-43f3-adb9-1747ef1d71ab",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "71062573-0b0a-4379-bfc1-c686eb3cabc0",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "555e9ab5-e3a6-4906-9d2f-36bacd30cb22",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "7bb1124f-6c45-4ca1-88c1-cce22714d300",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "c93f342b-1857-47d3-8822-d553761bb75b",
                "ordinal": 3
              }
            ],
            "lineageTag": "b089386b-0eee-4bf2-9261-2801d5c1341d"
          }
        ],
        "isHidden": true,
        "lineageTag": "8e5ec7bc-d666-482f-83c3-db0300794247",
        "partitions": [
          {
            "name": "LocalDateTable_d231e8cc-b6e1-4aeb-ba99-9dfd011195ca",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Produced'[Event D])), 1, 1), Date(Year(MAX('Produced'[Event D])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_d5950262-fe10-4a8b-8a21-c5c60762f765",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "fca84c38-6bb6-462f-8d2b-9aa8b0236c39",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "f636be5b-9a2c-4c92-8284-cacd93a0f452",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "a036b807-2862-47a3-bbf1-bfa8c56605ab",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "3cb29d47-eac7-4201-9eb7-2a2be4b802e7",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "7a66b02f-ca57-4947-a11d-77d156bee95d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "9aa047a9-1c85-4a72-8dc5-c3aa5e14923b",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "7e792bc6-7a1b-450a-96fc-4fcf45de7198",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "5a2e06a0-36a2-4f77-a378-96b2df197431",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "c48eecb5-9d45-41d0-8c38-2edc577e642b",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "fe4719ee-11da-48a2-9134-044f87725284",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "7790dfe8-5cf2-4ee2-8dda-f9b8760027f9",
                "ordinal": 3
              }
            ],
            "lineageTag": "dfa0281e-e04c-4107-9846-4b8b624c7e3f"
          }
        ],
        "isHidden": true,
        "lineageTag": "a40165f3-3e03-41c7-a1fc-7dffe58e4d89",
        "partitions": [
          {
            "name": "LocalDateTable_d5950262-fe10-4a8b-8a21-c5c60762f765",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Produced'[Event B])), 1, 1), Date(Year(MAX('Produced'[Event B])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_d85d4649-8aa3-4301-bd22-0e3c32565b8c",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "e34eaa11-3c43-4e2f-9715-8db7c7edd679",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "2bf968bb-646e-4bd4-b926-934ea78b3db3",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "679b1944-ded2-461e-9f66-91f719a99b1f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "36dcb017-3427-4bd8-ba21-9d6597bacbb4",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "ccf59dfa-e8c6-4cb9-907d-1aa4db58b474",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "7d4777c1-6462-4e99-a67c-a6ef7df6bf3f",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "0ba07a6a-9462-43bc-a1b0-28e0b11d2928",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "981c06c2-e52e-47d7-ac45-7dd36572d3d1",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "4681bef6-47b6-433b-83ad-2902d16c87fd",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "254885a9-a1df-46dd-83a7-d1746f7dcfce",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "743b2920-c37b-4a13-b632-8685b2771caa",
                "ordinal": 3
              }
            ],
            "lineageTag": "584da3ac-5a31-4b7e-9500-921796b9ee8c"
          }
        ],
        "isHidden": true,
        "lineageTag": "8e1839a8-0eed-4eb5-96d5-c2be249eff60",
        "partitions": [
          {
            "name": "LocalDateTable_d85d4649-8aa3-4301-bd22-0e3c32565b8c",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Planned'[Event A])), 1, 1), Date(Year(MAX('Planned'[Event A])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_806dce84-153c-4eb1-a52a-37e471658132",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "45791cd3-8253-4200-a785-937f2dc69548",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "dee021e4-3ee6-4b90-a9ac-1bb3ca0d1962",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "5a2ad720-3515-4162-818e-dddaaa40f85e",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "a68898aa-f525-477f-a8f9-5f271b7001a8",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "74739761-cd1b-4e36-aae5-e998381030da",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "bfc950d7-9608-4d5f-9fca-51fa99a6a937",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "1e9adeb4-a95e-4b38-9cfb-2d6cdd0970ad",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a4d72975-e800-4377-aab5-b3d605e079fc",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "ad86c4cf-c963-4288-b097-f0af087e0a5d",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "ee2784f9-4aed-47f1-a2ac-850af1ecbffd",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "c34a652f-8e61-493a-b15f-c3d309150e60",
                "ordinal": 3
              }
            ],
            "lineageTag": "672d28b9-7076-4b3a-a336-2093cafc7624"
          }
        ],
        "isHidden": true,
        "lineageTag": "1d0e5e2f-af1c-400e-aed4-f2be5206115d",
        "partitions": [
          {
            "name": "LocalDateTable_806dce84-153c-4eb1-a52a-37e471658132",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Planned'[Event D])), 1, 1), Date(Year(MAX('Planned'[Event D])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_09d7d9f5-9c46-4024-8288-33bda2c9c17e",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "30409679-d6b1-43c3-8fdc-b313789c7fac",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "72e605c4-72e7-403b-baef-7a94bf7dbbe4",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "03a4a02c-9230-40d9-a5a7-cd912e4cfc62",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "351e256b-f89b-4d4f-8c77-482b597b67f4",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "d8157d03-885a-4815-8723-38ab7ad413e6",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "898617a2-e23f-4638-bc75-ef57fddf6638",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "ede4dd3c-ccf4-4077-9ebf-2de0c6928cd1",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "a0a60b97-92f1-4f21-8cca-f12c01448b7a",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "d8d3091e-a69c-4241-8cef-381c6d7556ad",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "e142a284-1f68-483c-b57e-3c13ac2297c1",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "b3605727-15e4-4885-b085-efa83b6bd506",
                "ordinal": 3
              }
            ],
            "lineageTag": "465c4739-7357-449f-bc06-0e1b4603c692"
          }
        ],
        "isHidden": true,
        "lineageTag": "c59b379d-24ab-4423-8f6a-8f548a1bbbea",
        "partitions": [
          {
            "name": "LocalDateTable_09d7d9f5-9c46-4024-8288-33bda2c9c17e",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Planned'[Shipping Date])), 1, 1), Date(Year(MAX('Planned'[Shipping Date])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      },
      {
        "name": "LocalDateTable_f6d0dca3-3150-434d-9035-75bd2bc88740",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "6195020c-8ef3-444d-8afe-f4c786262f79",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Year",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "9990b6b5-b1a2-4dcd-9390-b4fb3683ef9d",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "471802ee-1129-434d-a1d9-ba0ea8f6c525",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Month",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "632c6567-f2fc-4116-bc37-0856b3a2456f",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "62cfc667-184a-4b90-a7c4-191618c2448f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Quarter",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Qtr \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "79027954-55df-45e5-b7ee-83323a474ea7",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Day",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "4db2c0f8-4e1a-4358-8b50-0526b78ffb04",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Year",
                "column": "Year",
                "lineageTag": "103117af-71a5-4e9e-b9be-265eff0bda5f",
                "ordinal": 0
              },
              {
                "name": "Quarter",
                "column": "Quarter",
                "lineageTag": "23d87ce2-46b5-4a38-b889-ecf030908a03",
                "ordinal": 1
              },
              {
                "name": "Month",
                "column": "Month",
                "lineageTag": "493d220e-580f-4b5d-b986-608f7e5ae6b7",
                "ordinal": 2
              },
              {
                "name": "Day",
                "column": "Day",
                "lineageTag": "32368898-d998-47c8-87a0-61a186116173",
                "ordinal": 3
              }
            ],
            "lineageTag": "dee4eed1-0766-4301-8d58-fcf7491ca960"
          }
        ],
        "isHidden": true,
        "lineageTag": "2df15cbd-5e68-48af-a2cb-a2688927d145",
        "partitions": [
          {
            "name": "LocalDateTable_f6d0dca3-3150-434d-9035-75bd2bc88740",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Planned'[Event C])), 1, 1), Date(Year(MAX('Planned'[Event C])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}